version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            npm install
      - run:
          name: build script
          command: |
            npx shadow-cljs release script

workflows:
  version: 2
  default:
    jobs:
      - build
